openapi: 3.0.3
info:
  title: Controle de Contas Bancárias
  description: |-
    API de estudos para controle bancário:
  version: 1.0-SNAPSHOT
servers:
  - url: https://testenvironment.org/api/v1
  - url: https://prodenvironment.org/api/v1
tags:
  - name: customers
    description: Customers maintenance endpoints
paths:
  /customer/{customerId}:
    get:
      tags:
        - customers
      summary: Find customer by ID
      description: Returns a single customer
      operationId: getCustomerById
      parameters:
        - name: customerId
          in: path
          description: ID of the customer to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer'
        400:
          description: Invalid ID
        404:
          description: Customer not found
    put:
      tags:
        - customers
  /customers:
    get:
      tags:
        - customers
      summary: Get all customers
      description: List all customers from the bank.
      operationId: getCustomers
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customers'

